%% WAD_first_s3_spm_diagnose_firstlvl_models
%
% This script runs diagnosis on first level analysis generated by 
% WAD_first_s2_spm_fit_firstlvl_models.m
%
% IT IS MADE TO BE CALLED FROM THE PREVIOUS SCRIPT RATHER THAN FOR
% STANDALONE USE
%__________________________________________________________________________
%
% authors: Lukas Van Oudenhove & Iris Coppieters
% date:   April, 2021
%
%__________________________________________________________________________
% @(#)% WAD_first_s3_spm_diagnose_firstlvl_models.m         v1.0      
% last modified: 2021/04/08
%

cd(logDir);
vifs = scn_spm_design_check([DSGN.modeldir, '\', sid(i).name],'events_only');
save('vifs','vifs');