%% WAD_first_s2_spm_fit_firstlvl_models
%
% This script runs first level analysis from 
% a CANlab style first level DSGN structure array and
% CANlab/spm style onset/duration and noise regressor files 
% using CANlab's canlab_glm_subject_levels function
%
% See canlab_glm_single_subject('dsgninfo'), or documentation in 
% Github\CanlabCore\CanlabCore\GLM_Batch_tools for details on first level
% analysis using CANlab tools
%
% This script is adapted by @lukasvo76 from the script
% 1) 2_spm_fit_single_trial_models.m by @bogpetre on Google Drive\CANlab\
% CANLAB Lab Member Documents\GLM_batch_tools\bogdan_paingen
% 2) MPA2_set_design_model1_blanca.m by @martaceko on
% Google Drive\CANlab\CANLAB Lab Member Documents\GLM_batch_tools\
% Marta_MPA2\MPA2code_1stlevel\Code
% contact @lukasvo76 if you need those original scripts
%
% DEPENDENCIES ON YOUR MATLAB PATH - SEE SETTINGS BELOW
% a) SPM12
% b) CANlab tools cloned from Github (see canlab.github.io)
% c) scripts folder for your project, including the function 
% WAD_get_firstlvl_dsgn_obj() called by this script
% 
% INPUTS 
% 1. DSGN structure array generated by the function 
% LaBGAS_get_firstlvl_dsgn_obj called from this script
%
% OUTPUT
% 1. estimated first level models in DSGN.modeldir
% 2. a directory and settings for diagnostics obtained by calling
% LaBGAS_3_spm_diagnose_firstlvl_models.m
%
% OPTIONS
% model
% choose between different models previously defined in 
% WAD_prep_s3_extract_confound_reg_fMRIprep.m
%__________________________________________________________________________
%
% authors: Lukas Van Oudenhove & Iris Coppieters
% date:   April, 2021
%
%__________________________________________________________________________
% @(#)% WAD_first_s2_spm_fit_firstlvl_models.m         v1.0      
% last modified: 2021/04/16
%
%% SETTINGS
%--------------------------------------------------------------------------

% addpath(genpath('C:\Users\lukas\Documents\GitHub\CanlabCore')); % add relevant CANlab tools folders and spm to Matlab path if they are not there yet
% addpath(genpath('C:\Users\lukas\Documents\GitHub\CanlabPrivate'));
% addpath(genpath('C:\Users\lukas\Documents\MATLAB\spm12'));
addpath(genpath('C:\Users\lukas\Dropbox (Dartmouth College)\4.Iris_WAD_MRI\scripts_windows')); % add our local path to the scriptsdir for this project

model = 'model_1_pictures';


%% CALL FUNCTION TO CREATE DSGN STRUCTURE ARRAY
%--------------------------------------------------------------------------

switch model
    case 'model_1_pictures'
        DSGN = WAD_get_firstlvl_dsgn_obj_model_1();
    case 'model_2_pictures_imagine'
        DSGN = WAD_get_firstlvl_dsgn_obj_model_2();
    case 'model_3_pictures_fir'
        DSGN = WAD_get_firstlvl_dsgn_obj_model_3();
    otherwise
        error('invalid model option, correct in settings');
end


%% CODE TO GENERATE ANALYSIS AND DIAGNOSTICS, AND PUBLISH REPORT
%--------------------------------------------------------------------------

sid = dir([DSGN.modeldir,'\sub-*']);

for i = 1:size(DSGN.subjects,2) % loop over subj
    
    % FIT FIRST LEVEL MODELS
    fprintf('Running on subject directory %s\n',DSGN.subjects{i});
    canlab_glm_subject_levels(DSGN,'subjects',DSGN.subjects(i),'overwrite');

    % SETUP FOR DIAGNOSIS
    logDir=[DSGN.modeldir, '\', sid(i).name, '\diagnostics'];
    mkdir(logDir);

    p = struct('useNewFigure', false, 'maxHeight', 800, 'maxWidth', 1600, ...
        'format', 'html', 'outputDir', logDir, ...
        'showCode', true);

    % RUN DIAGNOSIS
    publish('WAD_first_s3_spm_diagnose_firstlvl_models.m',p)
    
end